name: flutter_validators
description: A pure dart package of String validators and sanitizers. Inspired by validator.js.
version: 1.0.2
homepage: https://github.com/divyanshub024/flutter_validator
repository: https://github.com/divyanshub024/flutter_validator

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dev_dependencies:
  test: ^1.25.15
  flutter_lints: ^5.0.0