name: flutter_validators_dart
description: A pure dart package of String validators and sanitizers. Inspired by validator.js.
version: 0.1.0
homepage: https://github.com/divyanshub024/flutter_validator

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dev_dependencies:
  test: ^1.25.15